### ISSUE TITLE
External site support

### ISSUE THREAD

**Issue by SpikeHD** [eugenehp/tauri-plugin-gamepad#4]
Currently the way the plugin is built, it requires importing the package. When using Tauri to display an external website, this cannot be done, and the plugin can never be utilized. In my case, I'm displaying PokeRogue, so this would really benefit those on Raspberry Pi devices and such (see [related feature request](https://github.com/SpikeHD/RogueTop/issues/4))!

Thank you for this plugin, I believe I've attempted this before for something else and did not end up with the motivation to get very far :P

**Comment by eugenehp** [comment]
Assuming I got the external website part right, you're trying to inject the gamepad support to a third party website, you don't control.

If that's the case, have you looked into [injecting the script directly](https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.initialization_script)? 

Afterall the javascript logic, is just a bunch of subscriptions to the Tauri's internal invokes/subscribe methods.

**Comment by SpikeHD** [comment]
I have, yea, it's almost certainly because I'm on `2.0.0-rc` but it throws an error about the plugin not providing a manifest, and an error about the `target` argument of the `listen` function not being correct.

iirc plugins can also provide `initialization_script`s, so maybe an optional `autoinject` parameter could be introduced that removes the need to import?

**Comment by eugenehp** [comment]
Interesting idea, I'll look into it.

**Comment by eugenehp** [comment]
Tracking the progress here: https://github.com/DeveloperMindset-com/tauri-plugin-gamepad/tree/tauri-2.0.0-rc

**Comment by eugenehp** [comment]
Ok. New release has been published [here](https://crates.io/crates/tauri-plugin-gamepad/0.0.4).

Let me know if it works for you.
